version: "3"
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5001"
    env_file:
      - auth/.env
    depends_on:
      - mongo
      - rabbitmq
  concerts:
    build:
      context: ./concerts
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5002"
    env_file:
      - concerts/.env
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - concerts
volumes:
  mongo-data:
    